[package]
name = "pineflash"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
# egui_extras = "0.19.0"
zip-extract = "0.1.1"
ehttp = "0.2"
# poll-promise = "0.1"
poll-promise = "0.1"
tinyjson = "2.5.0"
egui-notify = "0.4"
rfd = "0.10.0"
regex = "1.6.0"
whoami = "1.2.3"
